### ISSUE TITLE
Dependency deprecation @ NPM install

### ISSUE THREAD

**Issue by newswim** [strongloop/strongloop#243]
Hi everyone, I executed the global npm install and received several deprecation warnings. Would it be problematic for me to update these manually or are there constraints I might not be aware of? Here are the warnings:

```
npm WARN deprecated MD5@1.2.2: deprecated, use lowercase 'md5@2.x' from now on

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'

npm WARN deprecated showdown@0.3.1: IMPORTANT hotfix
npm WARN deprecated react-tools@0.10.0: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
```

I'm running a MBP with Node v0.12.7 -- Thanks!

**Comment by sam-github** [comment]
Yes, it would be problematic, it could break strongloop, and it would not make strongloop work better.

Deprecations are an ad-hoc poorly used mechanism for module authors to communicate to consumers, in the absence of npmjs.org supporting any other way. For example, the showdown author published a backwards incompatible 1.x version, and would like people to use it, which is fair, but by deprecating it he now causes all users who are completely happy with there current version of showdown to have npm warnings in their install output. :-(

**Comment by rmg** [comment]
The use of `MD5` should be reasonably easy to fix, since it is a direct dependency of one of our modules.
 - strongloop/minkelite#18

The others, unfortunately, are fairly deeply nested :-(
```
strongloop -> generator-loopback -> yeoman-generator -> cheerio -> CSSselect
strongloop -> generator-loopback -> yeoman-generator -> cheerio -> CSSselect -> CSSwhat
strongloop -> loopback-sdk-angular-cli -> docular -> docular-doc-api-doc -> showdown
```

**Comment by rmg** [comment]
I don't think there's a need for a high level tracking issue, so I'm closing this now that the relevant upstream issues and PRs have been opened:
 - [x] issue: strongloop/minkelite#18 (closed by strongloop/minkelite#19)
 - [ ] issue: strongloop/generator-loopback#109
 - [ ] PR: strongloop/loopback-sdk-angular-cli#28
 - [ ] issue: strongloop/strong-arc#1488
